### ISSUE TITLE
 No number after minus sign in JSON at position 1

### ISSUE THREAD

**Issue by Bhavukarora03** [ZaharBerku/openai-speech-to-text#1]
⨯ RangeError [ERR_HTTP_INVALID_STATUS_CODE]: Invalid status code: 0
    at ServerResponse.writeHead (node:_http_server:352:11)
    at ServerResponse.writeHead (C:\Users\bhavu\OneDrive\Documents\GitHub\openai-speech-to-text\node_modules\next\dist\compiled\compression\index.js:46:263)
    at ServerResponse._implicitHeader (node:_http_server:338:8)
    at ServerResponse.end (C:\Users\bhavu\OneDrive\Documents\GitHub\openai-speech-to-text\node_modules\next\dist\compiled\compression\index.js:22:749)     
    at sendResponse (C:\Users\bhavu\OneDrive\Documents\GitHub\openai-speech-to-text\node_modules\next\dist\server\send-response.js:48:30)
    at doRender (C:\Users\bhavu\OneDrive\Documents\GitHub\openai-speech-to-text\node_modules\next\dist\server\base-server.js:1361:62)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async cacheEntry.responseCache.get.routeKind (C:\Users\bhavu\OneDrive\Documents\GitHub\openai-speech-to-text\node_modules\next\dist\server\base-server.js:1567:28)
    at async DevServer.renderToResponseWithComponentsImpl (C:\Users\bhavu\OneDrive\Documents\GitHub\openai-speech-to-text\node_modules\next\dist\server\base-server.js:1475:28)
    at async DevServer.renderPageComponent (C:\Users\bhavu\OneDrive\Documents\GitHub\openai-speech-to-text\node_modules\next\dist\server\base-server.js:1852:24)
    at async DevServer.renderToResponseImpl (C:\Users\bhavu\OneDrive\Documents\GitHub\openai-speech-to-text\node_modules\next\dist\server\base-server.js:1890:32)
    at async DevServer.pipeImpl (C:\Users\bhavu\OneDrive\Documents\GitHub\openai-speech-to-text\node_modules\next\dist\server\base-server.js:902:25)       
    at async NextNodeServer.handleCatchallRenderRequest (C:\Users\bhavu\OneDrive\Documents\GitHub\openai-speech-to-text\node_modules\next\dist\server\next-server.js:266:17)
    at async DevServer.handleRequestImpl (C:\Users\bhavu\OneDrive\Documents\GitHub\openai-speech-to-text\node_modules\next\dist\server\base-server.js:798:17) {
  code: 'ERR_HTTP_INVALID_STATUS_CODE'
}
 ⨯ SyntaxError: No number after minus sign in JSON at position 1
    at JSON.parse (<anonymous>)
    at parseJSONFromBytes (node:internal/deps/undici/undici:4747:19)
    at successSteps (node:internal/deps/undici/undici:4718:27)
    at fullyReadBody (node:internal/deps/undici/undici:1433:9)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async specConsumeBody (node:internal/deps/undici/undici:4727:7)
    at async POST (webpack-internal:///(rsc)/./src/app/api/speechToText/route.js:22:18)
    at async C:\Users\bhavu\OneDrive\Documents\GitHub\openai-speech-to-text\node_modules\next\dist\compiled\next-server\app-route.runtime.dev.js:6:62609

**Comment by ZaharBerku** [comment]
@Bhavukarora03 do you still have this problem?

**Comment by Bhavukarora03** [comment]
@ZaharBerku yeah fixed it, changed my api key to gpt-4 one. gpt-3.5 wasnt working
